<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>XPlane737NGPatchCli</AssemblyName>
    <Version>0.1.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../LevelUp.NavTableUpdater.Core/LevelUp.NavTableUpdater.Core.csproj" />
  </ItemGroup>

</Project>
